### ISSUE TITLE
InvalidPathException on Windows

### ISSUE THREAD

**Issue by alkekkonen** [alfa-laboratory/akita#70]
I got the following exception while executing `gradle clean test` task on my Windows machine. It looks like this issue is Windows-specific: it's okay on Mac. 

> java.lang.IllegalArgumentException: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Projects/project-folder-name/build/classes/test/../resources/blacklist
>     at com.codeborne.selenide.webdriver.AbstractDriverFactory.createInstanceOf(AbstractDriverFactory.java:50)
>     at com.codeborne.selenide.webdriver.DefaultDriverFactory.create(DefaultDriverFactory.java:17)
>     at com.codeborne.selenide.webdriver.WebDriverFactory.lambda$createWebDriver$1(WebDriverFactory.java:53)
>     at java.util.Optional.orElseGet(Optional.java:267)
>      …
> Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Projects/project-folder-name/build/classes/test/../resources/blacklist
>     at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
>     at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
>     at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
>     at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
>     at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
>     at java.nio.file.Paths.get(Paths.java:84)
>     at ru.alfabank.tests.core.helpers.BlackListManager.getResource(BlackListManager.java:61)
>     at ru.alfabank.tests.core.helpers.BlackListManager.fillBlackList(BlackListManager.java:46)
>     at ru.alfabank.tests.core.helpers.BlackList.setDefaultBlacklistEntries(BlackList.java:40)
>     at ru.alfabank.tests.core.helpers.BlackList.<init>(BlackList.java:29)
>     at ru.alfabank.tests.core.drivers.CustomDriverProvider.createDriver(CustomDriverProvider.java:72)
>     at com.codeborne.selenide.webdriver.AbstractDriverFactory.createInstanceOf(AbstractDriverFactory.java:42)
>     ... 83 more

**Comment by GannaChernyshova** [comment]
fixed here https://github.com/alfa-laboratory/akita/commit/062c426491825454c7fb3268091ecc605e924b85
